### ISSUE TITLE
New campaign can't be created

### ISSUE THREAD

**Issue by FeyScratcher** [ProgSys/pg_disatools#30]
Hello, I've only edited one thing on my project (the title screen), and for some reason it crashes when I try to make a new campaign. Is this just my computer being slow? Possibly, but I want to know whether or not it is.

**Comment by ProgSys** [comment]
Does even the simplest possible campaign crashes for you? 
You can send me over your files and I can have a look if I can reproduce it.
Edit:
Maybe I misunderstood a bit, what exactly have you edited and what crashes? The game or the map editor?

**Comment by FeyScratcher** [comment]
Disa Map Viewer (current version 0.3.0) hangs temporarily and then crashes when I use "add campaign" and then click "create." So far the only thing I have edited is the graphic title screen which I would assume isn't the problem.

**Comment by ProgSys** [comment]
So you used the File Manager to changed "NEW_WBG00.TX2" or "TITLEBG.TX2"? I will try to change them too and see what happens.

**Comment by FeyScratcher** [comment]
I changed "NEW_WBG00.TX2", since it is the English one.

**Comment by ProgSys** [comment]
So I have exported "NEW_WBG00.TX2" as an PNG, edited it, converted to to a TX2 using the TX2 Editor with the same format "Front (BGRA 16 colors)" and then used "Replace, keep name" inside the File Manager to import it back. After that on my end at least the Map Editor works fine after all that.
The only explanations I can muster right now is:
- The modified NEW_WBG00.TX2 uses a different format
- DATA.DAT got somehow corrupted or the order of the files was changed

The speed of your computer shouldn't matter, unless of course you use a toaster. I am afraid for a better analysis I would need to exactly know what you have done and if I can't reproduce it, I probably need to see your files. The terminal output of the Map Editor could also help.

**Comment by FeyScratcher** [comment]
I do use a computer that used to run windows 7 with a couple of 16 gig ram sticks shoved in it, so I don't know if that qualifies as a toaster, but I'll give you the files. [https://drive.google.com/drive/folders/11Hv5duI4TMWfTivvpKHVd8zZR3QtAfr6](url)

edit: the operating system is windows 10, sorry.

**Comment by ProgSys** [comment]
You will need to give me access to your google files or make them public.

**Comment by FeyScratcher** [comment]
Sorry, fixed it.
edit: I fixed the drive, not the campaign problem.

**Comment by ProgSys** [comment]
Thank your files! Still on my end they work totally fine, **but** I did find some clues that could create problems. 
I published a new version (v1.0.2) with improved error handling when creating a new campaign. Can you please try it out? Maybe it fixes your problem.

Just a question, I noticed that you unpacked TALK.DAT? Are you trying to modify the game scripts or dialog?

**Comment by FeyScratcher** [comment]
I was trying to, didn't, and I'll install the new version of map editor.

**Comment by FeyScratcher** [comment]
I am using the newest version of Disgaea tools, in which it has the version of the map editor I am using. I tried re-copying the actual game to see if the talk.dat was corrupted, nope, wasn't that.

**Comment by ProgSys** [comment]
I am a bit confused. So it still crashes when you try to create a new campaign when using v0.3.1 of the map editor?

**Comment by FeyScratcher** [comment]
Wait, 0.3.1, I have 0.3.0, but I installed disatools yesterday. Did you come out with an update today?

**Comment by FeyScratcher** [comment]
OH MY GOSH, I am so sorry.

**Comment by FeyScratcher** [comment]
Thank you, it worked, sorry for causing this problem.

**Comment by ProgSys** [comment]
> Wait, 0.3.1, I have 0.3.0, but I installed disatools yesterday. Did you come out with an update today?

**Comment by ProgSys** [comment]
> Wait, 0.3.1, I have 0.3.0, but I installed disatools yesterday. Did you come out with an update today?

No, it's a **new** version that I released **just for you** about 1 hour ago, with improvements that seems like fixed your problems^^

**Comment by FeyScratcher** [comment]
I know this is closed, but now that I can create the campaigns, how do you change between campaigns? Campaigns are what I think they are right? Etna mode is a different campaign then Laharal (main), right?

**Comment by FeyScratcher** [comment]
Also thanks for making the special version for me, I'll try to contribute with bugs if I can.

**Comment by ProgSys** [comment]
No. Campaigns in this case are more like map packs , but that can contain a story (but its a bit tricky to add one right now ). After you created one it can be selected at the dimension gate lady. It should be her first entry in the list. There are some very basic instructions here: https://github.com/ProgSys/pg_disatools/wiki/Map-Editor

For more question better create a new issue, as this one is closed now. 
Good night!
